version: '2'
services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - db
      - test_db
    environment:
      - DB_URL=postgresql://postgres@db:5432/postgres
    entrypoint:
      ./entrypoint_web.sh
    volumes:
      - "./server:/thupoll/server"

  db:
    image: postgres:11
    volumes:
      - psql_data:/var/lib/postgresql/data
    expose:
      - "5432"

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:5000
    depends_on:
      - web

  # run container for executing tests
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    depends_on:
      - test_db
    environment:
      - TEST_DB_URL=postgresql://postgres@test_db:5432/postgres
    tty:
      true
    entrypoint:
      bash
    volumes:
      - "./server:/thupoll/server"

  test_db:
    image: postgres:11
    expose:
      - "5432"


volumes:
  psql_data:
