version: '2'
services:

  ##########
  #  PROD  #
  ##########

  base:
    image: octoman/base
    build:
      context: .
      dockerfile: docker/base/Dockerfile

  web:
    image: octoman/web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - db
      - test_db
    environment:
      - DB_URL=postgresql://postgres@db:5432/postgres
      - LOG_LEVEL=INFO
      - SERVICE_NAME=api
    volumes:
      - "./thupoll:/app/thupoll"
    restart: always

  db:
    image: postgres:11
    volumes:
      - psql_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always

  ##########
  #  TEST  #
  ##########

  # run container for executing tests
  test:
    image: octoman/test
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    depends_on:
      - test_db
    environment:
      - DB_URL=postgresql://postgres@test_db:5432/postgres
      - LOG_LEVEL=DEBUG
      - SERVICE_NAME=bash
    tty:
      true
    volumes:
      - "./:/app/"

  test_db:
    image: postgres:11
    expose:
      - "5432"


volumes:
  psql_data:
