version: '3'
services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://postgres@db:5432/postgres
    entrypoint:
      ./entrypoint_web.sh

  db:
    image: postgres:11
    ports:  # FIXME for tesing only; remove for production
      - 5432:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
    volumes:
      - psql_data:/var/lib/postgresql/data
    expose:
      - "5432"

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:5000
    depends_on:
      - web

volumes:
  psql_data:
