version: '2'
services:

  ##########
  #  PROD  #
  ##########

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - db
      - test_db
    environment:
      - DB_URL=postgresql://postgres@db:5432/postgres
      - LOG_LEVEL=DEBUG
      - SERVICE_NAME=api
    volumes:
      - "./thupoll:/app/thupoll"

  db:
    image: postgres:11
    volumes:
      - psql_data:/var/lib/postgresql/data
    expose:
      - "5432"

  ##########
  #  TEST  #
  ##########

  # run container for executing tests
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    depends_on:
      - test_db
    environment:
      - DB_URL=postgresql://postgres@test_db:5432/postgres
      - SERVICE_NAME=bash
    tty:
      true
    volumes:
      - "./thupoll:/app/thupoll"

  test_db:
    image: postgres:11
    expose:
      - "5432"


volumes:
  psql_data:
