FROM python:3

RUN apt-get update && \
    apt-get install -y net-tools netcat && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install --no-cache -r requirements.txt

ENV PYTHONPATH=/polls_api

COPY entrypoint_web.sh $PYTHONPATH/entrypoint_web.sh
COPY polls_api $PYTHONPATH/polls_api
COPY tests $PYTHONPATH/tests

WORKDIR /$PYTHONPATH

CMD sh entrypoint_web.sh
