"""empty message

Revision ID: 0478d89f9e45
Revises: 58a47deb30fa
Create Date: 2019-05-03 12:29:25.415711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0478d89f9e45'
down_revision = '58a47deb30fa'
branch_labels = None
depends_on = None


def upgrade():
    # alembic `alter_column` can't evaluate sql with USING statement
    op.execute('''
        ALTER TABLE people
            ALTER COLUMN telegram_login TYPE BIGINT USING telegram_login::integer;
    ''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'telegram_login',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
