"""empty message

Revision ID: 15500d089742
Revises: b4c2e2c75704
Create Date: 2019-03-15 06:13:40.683756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15500d089742'
down_revision = 'b4c2e2c75704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'people', ['telegram_login'])
    op.create_foreign_key(None, 'people', 'role', ['role_id'], ['id'])
    op.add_column('poll', sa.Column('meet_date', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_foreign_key(None, 'theme', 'theme_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'theme', 'people', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'theme', 'people', ['author_id'], ['id'])
    op.create_index('theme_poll_poll_id_theme_id_uidx', 'theme_poll', ['poll_id', 'theme_id'], unique=True)
    op.create_foreign_key(None, 'theme_poll', 'theme', ['theme_id'], ['id'])
    op.create_foreign_key(None, 'theme_poll', 'poll', ['poll_id'], ['id'])
    op.create_unique_constraint(None, 'theme_status', ['name'])
    op.create_index('volume_people_id_people_id_uidx', 'volume', ['people_id', 'themepoll_id'], unique=True)
    op.create_foreign_key(None, 'volume', 'people', ['people_id'], ['id'])
    op.create_foreign_key(None, 'volume', 'theme_poll', ['themepoll_id'], ['id'])

    op.execute('''INSERT INTO theme_status (id, name) VALUES (1, 'new');''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volume', type_='foreignkey')
    op.drop_constraint(None, 'volume', type_='foreignkey')
    op.drop_index('volume_people_id_people_id_uidx', table_name='volume')
    op.drop_constraint(None, 'theme_status', type_='unique')
    op.drop_constraint(None, 'theme_poll', type_='foreignkey')
    op.drop_constraint(None, 'theme_poll', type_='foreignkey')
    op.drop_index('theme_poll_poll_id_theme_id_uidx', table_name='theme_poll')
    op.drop_constraint(None, 'theme', type_='foreignkey')
    op.drop_constraint(None, 'theme', type_='foreignkey')
    op.drop_constraint(None, 'theme', type_='foreignkey')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('poll', 'meet_date')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='unique')

    op.execute('''DELETE FROM theme_status;''')
    # ### end Alembic commands ###
