"""empty message

Revision ID: 58a47deb30fa
Revises: 51506d1f9d1b
Create Date: 2019-03-31 18:47:47.347288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a47deb30fa'
down_revision = '51506d1f9d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespace',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('people_namespace',
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('namespace_code', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['namespace_code'], ['namespace.code'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('people_id', 'namespace_code')
    )
    op.add_column('poll', sa.Column('namespace_code', sa.String(), nullable=False))
    op.create_index(op.f('ix_poll_namespace_code'), 'poll', ['namespace_code'], unique=False)
    op.create_foreign_key(None, 'poll', 'namespace', ['namespace_code'], ['code'])
    op.add_column('theme', sa.Column('namespace_code', sa.String(), nullable=False))
    op.create_index(op.f('ix_theme_namespace_code'), 'theme', ['namespace_code'], unique=False)
    op.create_foreign_key(None, 'theme', 'namespace', ['namespace_code'], ['code'])
    op.create_index(op.f('ix_theme_poll_theme_id'), 'theme_poll', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_poll_theme_id'), table_name='theme_poll')
    op.drop_constraint(None, 'theme', type_='foreignkey')
    op.drop_index(op.f('ix_theme_namespace_code'), table_name='theme')
    op.drop_column('theme', 'namespace_code')
    op.drop_constraint(None, 'poll', type_='foreignkey')
    op.drop_index(op.f('ix_poll_namespace_code'), table_name='poll')
    op.drop_column('poll', 'namespace_code')
    op.drop_table('people_namespace')
    op.drop_table('namespace')
    # ### end Alembic commands ###
