"""empty message

Revision ID: 6c12656bbaf4
Revises: 0478d89f9e45
Create Date: 2019-05-05 19:50:10.087360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c12656bbaf4'
down_revision = '0478d89f9e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        ALTER TABLE namespace ALTER COLUMN telegram_chat_id TYPE BIGINT;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        ALTER TABLE namespace ALTER COLUMN telegram_chat_id TYPE INT;
    ''')
    # ### end Alembic commands ###
