"""empty message

Revision ID: 50061cdd0a08
Revises: 
Create Date: 2019-02-28 21:24:13.274467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50061cdd0a08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('reporter', sa.Integer(), nullable=True),
    sa.Column('change_date', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('create', 'preparing', 'planning', 'discarded', 'done', name='lecture_status'), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture')
    op.drop_table('user')
    # ### end Alembic commands ###
