"""empty message

Revision ID: 98f53ae55150
Revises: 1332f2c970f9
Create Date: 2019-02-28 22:39:56.334102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98f53ae55150'
down_revision = '1332f2c970f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'poll', 'change_date',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'))
    op.alter_column(
        'poll', 'created_date',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'))
    op.alter_column(
        'poll', 'expire_date',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False)
    op.alter_column(
        'theme', 'author_id',
        existing_type=sa.INTEGER(),
        nullable=False)
    op.alter_column(
        'theme', 'change_date',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'))
    op.alter_column(
        'theme', 'created_date',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'))
    op.alter_column(
        'theme', 'reporter_id',
        existing_type=sa.INTEGER(),
        nullable=False)
    op.alter_column('theme', 'status_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('theme', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('theme_poll', 'poll_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('theme_poll', 'theme_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('user', 'change_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('user', 'telegram_login',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('volume', 'created_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('volume', 'themepoll_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('volume', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volume', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('volume', 'themepoll_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('volume', 'created_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('user', 'telegram_login',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('user', 'created_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('user', 'change_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('theme_poll', 'theme_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('theme_poll', 'poll_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('theme', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('theme', 'status_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('theme', 'reporter_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('theme', 'created_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('theme', 'change_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('theme', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('poll', 'expire_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('poll', 'created_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('poll', 'change_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
