"""empty message

Revision ID: b74f90141cb1
Revises: 98f53ae55150
Create Date: 2019-02-28 23:27:26.059374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b74f90141cb1'
down_revision = '98f53ae55150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('telegram_login', sa.String(), nullable=False),
                    sa.Column('created_date', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('change_date', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('user')
    op.add_column('volume', sa.Column(
        'people_id', sa.Integer(), nullable=False))
    op.drop_column('volume', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volume', sa.Column('user_id', sa.INTEGER(),
                                      autoincrement=False, nullable=False))
    op.drop_column('volume', 'people_id')
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('telegram_login', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.Column('change_date', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='user_pkey')
                    )
    op.drop_table('people')
    # ### end Alembic commands ###
